"""PreparePR node handler.

Drives the full GitHub integration for a run:

  1. Check whether the project already has a GitHub repo; create one if not.
  2. Resolve the authenticated user's login (for head-ref filtering).
  3. Create feature branch ``id8/run-{run_id}`` (idempotent).
  4. Push all files from the latest ``code_snapshot`` artifact.
  5. Open a pull-request (idempotent — no duplicate PRs per run).
  6. Poll CI check runs until all complete or the 10-minute timeout fires.
  7. If all checks pass: squash-merge the PR.
  8. If checks fail or time out: return ``"failure"`` with details.

Branch protection is respected by design — code is never pushed directly to
the default branch.
"""
from __future__ import annotations

import logging
import uuid
from typing import Any

from sqlalchemy import select

from app.github.auth import resolve_github_auth
from app.github.client import (
    GitHubAuthError,
    GitHubChecksTimedOutError,
    GitHubClient,
    GitHubConflictError,
    GitHubError,
    GitHubNotFoundError,
    GitHubRateLimitError,
    PrInfo,
    _parse_owner_repo,
)
from app.models.enums import ArtifactType
from app.models.project import Project
from app.models.project_artifact import ProjectArtifact
from app.orchestrator.base import NodeHandler, NodeResult, RunContext
from app.orchestrator.retry import RateLimitError

logger = logging.getLogger("id8.orchestrator.handlers.prepare_pr")

_CHECK_POLL_TIMEOUT = 600.0  # 10 minutes
_PR_BODY_TEMPLATE = """\
## ID8 Generated Code

**Run ID:** `{run_id}`
**Project:** `{project_id}`

### Artifacts
- Code snapshot generated by WriteCode node
- Security gate: passed (no unresolved high/critical findings)

This pull request was created automatically by the ID8 orchestrator.
Approve and merge to proceed to the Deploy stage.
"""


class PreparePRHandler(NodeHandler):
    """Create branch, push code, open PR, poll checks, and merge on pass."""

    async def execute(self, ctx: RunContext) -> NodeResult:
        # 1. Load code snapshot.
        code_snapshot = await _load_code_snapshot(ctx)
        if code_snapshot is None:
            return NodeResult(
                outcome="failure",
                error="No code_snapshot artifact found; PreparePR cannot proceed",
            )

        files: list[dict[str, str]] = code_snapshot.get("files", [])
        if not files:
            return NodeResult(
                outcome="failure",
                error="code_snapshot contains no files to push",
            )

        # 2. Resolve GitHub auth.
        auth = resolve_github_auth()
        if auth.mode == "none":
            return NodeResult(
                outcome="failure",
                error=(
                    "No GitHub credentials configured. "
                    "Set GITHUB_TOKEN or GITHUB_APP_ID + GITHUB_APP_PRIVATE_KEY."
                ),
            )

        client = GitHubClient(auth)

        try:
            return await _run_github_flow(ctx, client, files)
        except GitHubRateLimitError as exc:
            raise RateLimitError(
                f"GitHub rate limit: {exc}",
                retry_after_seconds=exc.retry_after,
            ) from exc
        except GitHubAuthError as exc:
            return NodeResult(
                outcome="failure",
                error=f"GitHub authentication failed: {exc}",
            )
        except GitHubError as exc:
            return NodeResult(
                outcome="failure",
                error=f"GitHub API error: {exc}",
            )


# ---------------------------------------------------------------------------
# Core flow (extracted so the top-level handler stays clean)
# ---------------------------------------------------------------------------


async def _run_github_flow(
    ctx: RunContext,
    client: GitHubClient,
    files: list[dict[str, str]],
) -> NodeResult:
    # 3. Determine owner from auth / existing repo.
    project = await _load_project(ctx)
    if project is None:
        return NodeResult(
            outcome="failure",
            error=f"Project {ctx.project_id} not found",
        )

    branch_name = f"id8/run-{ctx.run_id}"

    # 4. Resolve or create the repository.
    if project.github_repo_url:
        owner, repo_name = _parse_owner_repo(project.github_repo_url)
        logger.info(
            "Using existing repo %s/%s for project=%s",
            owner,
            repo_name,
            ctx.project_id,
        )
    else:
        owner, repo_name = await _create_project_repo(ctx, client, project)
        logger.info(
            "Created new repo %s/%s for project=%s",
            owner,
            repo_name,
            ctx.project_id,
        )

    # 5. Create feature branch (idempotent).
    default_branch = await _ensure_branch(client, owner, repo_name, branch_name)
    logger.info("Feature branch '%s' ready on %s/%s", branch_name, owner, repo_name)

    # 6. Resume idempotency: if a closed PR already exists for this run branch,
    # do not push new commits or create a duplicate PR.
    closed_pr = await _find_closed_pull_request(client, owner, repo_name, branch_name)
    if closed_pr is not None:
        metadata = {
            "github_repo_url": project.github_repo_url,
            "branch_name": branch_name,
            "pr_url": closed_pr.html_url,
            "pr_number": closed_pr.number,
            "check_statuses": [],
        }
        if closed_pr.merged:
            if closed_pr.merge_commit_sha:
                metadata["merge_commit_sha"] = closed_pr.merge_commit_sha
            await _persist_prepare_pr_metadata(ctx, metadata)
            logger.info(
                "Closed merged PR #%d already exists for run=%s; treating PreparePR as idempotent success",
                closed_pr.number,
                ctx.run_id,
            )
            return NodeResult(outcome="success", context_updates=metadata)

        await _persist_prepare_pr_metadata(ctx, metadata)
        return NodeResult(
            outcome="failure",
            error=(
                f"Existing PR #{closed_pr.number} for branch '{branch_name}' is closed "
                "without merge; manual intervention required"
            ),
            context_updates=metadata,
        )

    # 7. Push files.
    commit_sha = await client.push_files(
        owner,
        repo_name,
        branch_name,
        files,
        commit_message=f"chore(id8): generate code for run {ctx.run_id}",
    )
    logger.info(
        "Pushed %d files to %s/%s@%s (commit=%s)",
        len(files),
        owner,
        repo_name,
        branch_name,
        commit_sha,
    )

    # 8. Create or find the PR (idempotent).
    pr_info = await _ensure_pull_request(
        client,
        owner,
        repo_name,
        branch_name,
        base=default_branch,
        ctx=ctx,
    )
    logger.info(
        "PR #%d ready: %s",
        pr_info.number,
        pr_info.html_url,
    )

    # 9. Poll check runs.
    try:
        check_runs = await client.poll_checks(
            owner,
            repo_name,
            pr_info.head_sha,
            timeout=_CHECK_POLL_TIMEOUT,
        )
    except GitHubChecksTimedOutError as exc:
        metadata = {
            "github_repo_url": project.github_repo_url,
            "branch_name": branch_name,
            "pr_url": pr_info.html_url,
            "pr_number": pr_info.number,
            "check_statuses": [],
        }
        await _persist_prepare_pr_metadata(ctx, metadata)
        return NodeResult(outcome="failure", error=str(exc), context_updates=metadata)

    check_statuses = [
        {
            "name": r.name,
            "status": r.status,
            "conclusion": r.conclusion,
            "url": r.html_url,
        }
        for r in check_runs
    ]

    # 10. Evaluate check results.
    failed_checks = [
        r for r in check_runs if r.status == "completed" and r.conclusion not in ("success", "neutral", "skipped", None)
    ]
    if failed_checks:
        names = ", ".join(r.name for r in failed_checks)
        logger.warning(
            "PR #%d checks failed for run=%s: %s",
            pr_info.number,
            ctx.run_id,
            names,
        )
        metadata = {
            "github_repo_url": project.github_repo_url,
            "branch_name": branch_name,
            "pr_url": pr_info.html_url,
            "pr_number": pr_info.number,
            "check_statuses": check_statuses,
        }
        await _persist_prepare_pr_metadata(ctx, metadata)
        return NodeResult(
            outcome="failure",
            error=f"CI checks failed: {names}",
            context_updates=metadata,
        )

    # 11. Merge.
    try:
        merge_result = await client.merge_pull_request(owner, repo_name, pr_info.number)
    except GitHubConflictError as exc:
        metadata = {
            "github_repo_url": project.github_repo_url,
            "branch_name": branch_name,
            "pr_url": pr_info.html_url,
            "pr_number": pr_info.number,
            "check_statuses": check_statuses,
        }
        await _persist_prepare_pr_metadata(ctx, metadata)
        return NodeResult(
            outcome="failure",
            error=f"PR merge blocked: {exc}",
            context_updates=metadata,
        )

    logger.info(
        "PR #%d merged (sha=%s) for run=%s",
        pr_info.number,
        merge_result.sha,
        ctx.run_id,
    )

    metadata = {
        "github_repo_url": project.github_repo_url,
        "branch_name": branch_name,
        "pr_url": pr_info.html_url,
        "pr_number": pr_info.number,
        "merge_commit_sha": merge_result.sha,
        "check_statuses": check_statuses,
    }
    await _persist_prepare_pr_metadata(ctx, metadata)
    return NodeResult(outcome="success", context_updates=metadata)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


async def _load_code_snapshot(ctx: RunContext) -> dict[str, Any] | None:
    result = await ctx.db.execute(
        select(ProjectArtifact)
        .where(
            ProjectArtifact.run_id == ctx.run_id,
            ProjectArtifact.artifact_type == ArtifactType.CODE_SNAPSHOT,
        )
        .order_by(ProjectArtifact.version.desc())
        .limit(1)
    )
    artifact = result.scalar_one_or_none()
    return artifact.content if artifact is not None else None


async def _latest_code_snapshot_artifact(ctx: RunContext) -> ProjectArtifact | None:
    result = await ctx.db.execute(
        select(ProjectArtifact)
        .where(
            ProjectArtifact.run_id == ctx.run_id,
            ProjectArtifact.artifact_type == ArtifactType.CODE_SNAPSHOT,
        )
        .order_by(ProjectArtifact.version.desc())
        .limit(1)
    )
    return result.scalar_one_or_none()


async def _persist_prepare_pr_metadata(ctx: RunContext, metadata: dict[str, Any]) -> None:
    """Persist GitHub/PR metadata onto the latest code_snapshot artifact."""
    artifact = await _latest_code_snapshot_artifact(ctx)
    if artifact is None:
        return

    content = dict(artifact.content or {})
    github_meta = dict(content.get("__github", {}))
    github_meta.update(metadata)
    content["__github"] = github_meta
    artifact.content = content
    await ctx.db.flush()


async def _load_project(ctx: RunContext) -> Project | None:
    result = await ctx.db.execute(select(Project).where(Project.id == ctx.project_id))
    return result.scalar_one_or_none()


async def _create_project_repo(
    ctx: RunContext,
    client: GitHubClient,
    project: Project,
) -> tuple[str, str]:
    """Create a new GitHub repo and persist its URL on the project record."""
    repo_name = _generate_repo_name(ctx.project_id)

    user_data = await client.get_authenticated_user()
    owner: str = user_data["login"]

    repo_info = await client.create_repo(repo_name, private=True)

    # Persist repo URL so future runs/resumes find it.
    project.github_repo_url = repo_info.html_url
    await ctx.db.flush()

    return owner, repo_info.name


def _generate_repo_name(project_id: uuid.UUID) -> str:
    """Derive a stable, slug-safe repo name from the project UUID."""
    short = str(project_id).replace("-", "")[:12]
    return f"id8-{short}"


async def _ensure_branch(
    client: GitHubClient,
    owner: str,
    repo: str,
    branch_name: str,
) -> str:
    """Create the feature branch if it doesn't exist.

    Returns the default branch name (needed for PR base).
    """
    repo_info = await client.get_repo(owner, repo)
    default_branch = repo_info.default_branch

    try:
        await client.get_branch(owner, repo, branch_name)
        logger.info("Branch '%s' already exists on %s/%s — reusing", branch_name, owner, repo)
    except GitHubNotFoundError:
        try:
            await client.create_branch(owner, repo, default_branch, branch_name)
        except GitHubConflictError:
            # Race condition: another process created it just now.
            logger.info("Branch '%s' created concurrently on %s/%s — ok", branch_name, owner, repo)

    return default_branch


async def _ensure_pull_request(
    client: GitHubClient,
    owner: str,
    repo: str,
    branch_name: str,
    *,
    base: str,
    ctx: RunContext,
) -> Any:
    """Return an existing PR for this branch, or create a new one."""
    # Check for an existing open PR from this branch.
    existing = await client.list_pull_requests(
        owner, repo, head=f"{owner}:{branch_name}", state="open"
    )
    if existing:
        logger.info(
            "Found existing PR #%d for branch '%s' on %s/%s — reusing",
            existing[0].number,
            branch_name,
            owner,
            repo,
        )
        return existing[0]

    title = _build_pr_title(ctx)
    body = _PR_BODY_TEMPLATE.format(
        run_id=ctx.run_id,
        project_id=ctx.project_id,
    )
    return await client.create_pull_request(
        owner,
        repo,
        head=branch_name,
        base=base,
        title=title,
        body=body,
    )


async def _find_closed_pull_request(
    client: GitHubClient,
    owner: str,
    repo: str,
    branch_name: str,
) -> PrInfo | None:
    """Return a closed PR for this run branch if one exists and no open PR exists."""
    prs = await client.list_pull_requests(
        owner,
        repo,
        head=f"{owner}:{branch_name}",
        state="all",
    )
    if not prs:
        return None

    if any(pr.state == "open" for pr in prs):
        return None

    for pr in prs:
        if pr.merged:
            return pr
    return prs[0]


def _build_pr_title(ctx: RunContext) -> str:
    """Build a human-readable PR title from the workflow context."""
    prompt: str = ctx.workflow_payload.get("initial_prompt", "")
    if prompt:
        # Truncate to a reasonable headline length.
        truncated = prompt[:72].strip()
        if len(prompt) > 72:
            truncated += "…"
        return f"feat(id8): {truncated}"
    return f"feat(id8): generated code for run {ctx.run_id}"
